name: Build and Test My Grades App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display Softuni username
      run: echo "ystefanova"
  
  run-ui-tests:
    needs: build_and_run_unit_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Run App
      run: npm run start &
    - name: Run UI tests
      run: npm run test:ui

  deploy-to-prod:
    needs: run-ui-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true